name: Dagger Update

on:
  workflow_dispatch: # manually triggered
    inputs:
      environment:
        description: 'Environment name (one of: dev, qa, tnet, prod)'
        required: true
        default: 'dev'

env:
  # Dagger
  DAGGER_PLAN: ci/plans/cd-manager.cue
  STATUS_PLAN: ci/plans/status.cue
  DAGGER_LOG_FORMAT: "plain"
  PIPELINE_TOOLS_VER: "0.2.1"
  # Secrets
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  # GitHub
  RUN_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  STATUS_URL: "https://api.github.com/repos/3box/pipeline-tools/statuses/${{ github.sha }}"
  BRANCH: ${{ github.head_ref || github.ref_name }}
  SHA: ${{ github.sha }}

jobs:
  update_dagger_project:
    runs-on: ubuntu-latest
    steps:
      -
        name: Install Dagger
        uses: dagger/dagger-for-github@v3
        with:
          install-only: true
      -
        name: Setup Dagger
        run: |
            dagger project init
            dagger project update
            dagger project update "github.com/3box/pipeline-tools/ci@v${{ env.PIPELINE_TOOLS_VER }}"
